replicaCount: 1
dockerized: true
serviceId: "myservice"
clusterId: "mycluster"
loggerTypes: "Console"
loglevel: "Warning"

image1:
  ## Image location, NOT including the tag
  repository: skunklab/piraeus-tcp-gateway
  ## Image tag
  tag: v3.0 
  pullPolicy: IfNotPresent
  

service: 
  type: ClusterIP




