apiVersion: v1
description: A Helm chart for Piraeus Orleans cluster
name: piraeus-silo
version: 0.0.2
icon: https://avatars2.githubusercontent.com/u/25301165?s=400&v=4
appVersion: 0.0.2
keywords:
  - piraeus
  - orleans
  - piraeus orleans
home: https://github.com/skunklab/skunklab.core
sources:
  - https://github.com/skunklab/skunklab.core
maintainers:
  - name: Matt Long
    email: malong@microsoft.com
tillerVersion: ">=2.7.0-rc1"