apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udp
  labels:
    app: udp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: udp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: udp
      component: udp
  template:
    metadata:
      labels:
        app: udp
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: udp
    spec:
      containers: 
        - name: udp       
          image: {{ .Values.image1.repository }}:{{ .Values.image1.tag }}
          imagePullPolicy: {{ .Values.image1.pullPolicy }}
          env:
          - name: OR_Dockerized
            value: {{ .Values.dockerized | quote }}
          - name: PI_LogLevel
            value: {{ .Values.loglevel | quote }}
          - name: PI_LoggerTypes
            value: {{ .Values.loggerTypes | quote }}
          - name: OR_ClusterId
            value: {{ .Values.clusterId | quote }}
          - name: OR_ServiceId
            value: {{ .Values.serviceId | quote }}
          - name: OR_DataConnectionString
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataConnectionString 
          - name: PI_ClientIdentityNameClaimType
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientIdentityNameClaimType 
          - name: PI_ClientIssuer
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientIssuer  
          - name: PI_ClientAudience
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientAudience 
          - name: PI_ClientTokenType
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientTokenType
          - name: PI_ClientSymmetricKey
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientSymmetricKey 
          - name: PI_CoapAuthority
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: coapAuthority  
          - name: PI_AuditConnectionString
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: auditConnectionString      
          ports:
          - containerPort: 5683
          readinessProbe:
            tcpSocket:
              port: 5683
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 5683
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2          
          - containerPort: 5883
          readinessProbe:
            tcpSocket:
              port: 5883
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 5883
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2          
      nodeSelector:
        pool: nodepool1