apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  dataConnectionString: {{ required "A value is required for the orleans dataConnectionString" .Values.dataConnectionString }}    
  auditConnectionString : {{ required "A value is required for writing audit records" .Values.auditConnectionString }}  
  clientIdentityNameClaimType : {{ required "A value is required for unique claim type that identifies a connection" .Values.clientIdentityNameClaimType }}  
  clientIssuer : {{ required "A value is required for the claim type of the token issuer" .Values.clientIssuer }}  
  clientAudience : {{ required "A value is required for the claim type of the token audience" .Values.clientAudience }} 
  clientTokenType : {{ required "A value is required for the token type of the security token" .Values.clientTokenType }} 
  clientSymmetricKey : {{ required "A value is required for the symmetric key base64 encoded of key that signs the security token" .Values.clientSymmetricKey }} 
  coapAuthority : {{ required "A value is required CoAP authority for CoAP messages" .Values.coapAuthority }} 
  