apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-mgmt
  labels:
    app: {{ template "fullname" . }}-mgmt
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: mgmt
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mgmt
      component: mgmt
  template:
    metadata:
      labels:
        app: mgmt
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: mgmt
    spec:      
      containers:
        - name: mgmt     
          image: {{ .Values.image1.repository }}:{{ .Values.image1.tag }}
          imagePullPolicy: {{ .Values.image1.pullPolicy }}
          env:
          - name: OR_Dockerized
            value: {{ .Values.dockerized | quote }}
          - name: PI_LogLevel
            value: {{ .Values.loglevel | quote }}
          - name: PI_LoggerTypes
            value: {{ .Values.loggerTypes | quote }}
          - name: OR_ClusterId
            value: {{ .Values.clusterId | quote }}
          - name: OR_ServiceId
            value: {{ .Values.serviceId | quote }}
          - name: OR_DataConnectionString
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dataConnectionString  
          - name: PI_ManagementApiIssuer
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: managementApiIssuer 
          - name: PI_ManagementApiAudience
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: managementApiAudience  
          - name: PI_ManagmentApiSymmetricKey
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: managmentApiSymmetricKey   
          - name: PI_ManagementApiSecurityCodes
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: managementApiSecurityCodes                
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2        
      nodeSelector:
        pool: nodepool1